/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orderingSystem;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author sofiagarcia
 */
public class OrderConfirmation extends javax.swing.JFrame {

    /**
     * Creates new form OrderConfirmation
     */
    public OrderConfirmation() {
        initComponents();
    }
    
    public OrderConfirmation(Order order) {
        initComponents();
        this.jlbDistributorNameTitle.setText("Pedido al distribuidor " + order.getDistributor());
        this.jLabelConfirmedOrderText.setText(order.getQuantity() + " unidades del " + order.getType() + " " + order.getName());
        String branch = order.getBranch();
        if(branch == "Principal") {
            this.jLabelConfirmedOrderAddress.setText("Para la farmacia situada en Calle de la Rosa n.28");
        } else {
            this.jLabelConfirmedOrderAddress.setText("Para la farmacia situada en Calle Alcazabilla n. 3");
        }
    }


    
    public void close() {
        WindowEvent  closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        getToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSendOrder = new javax.swing.JButton();
        jButtonCancelOrder = new javax.swing.JButton();
        jlbDistributorNameTitle = new javax.swing.JLabel();
        jLabelConfirmedOrderText = new javax.swing.JLabel();
        jLabelConfirmedOrderAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSendOrder.setText("Enviar pedido");
        jButtonSendOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendOrderActionPerformed(evt);
            }
        });

        jButtonCancelOrder.setText("Cancelar pedido");
        jButtonCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelOrderActionPerformed(evt);
            }
        });

        jlbDistributorNameTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbDistributorNameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelConfirmedOrderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelConfirmedOrderAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelConfirmedOrderAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelOrder)
                        .addGap(106, 106, 106)
                        .addComponent(jButtonSendOrder))
                    .addComponent(jLabelConfirmedOrderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbDistributorNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlbDistributorNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelConfirmedOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelConfirmedOrderAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSendOrder)
                    .addComponent(jButtonCancelOrder))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelOrderActionPerformed
        this.close();
        Pharmacy pharmacy = new Pharmacy();
        pharmacy.setVisible(true);
    }//GEN-LAST:event_jButtonCancelOrderActionPerformed

    private void jButtonSendOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendOrderActionPerformed
        // TODO add your handling code here:
        System.out.println("Pedido enviado!" );
        JOptionPane.showMessageDialog(rootPane, "Pedido Enviado!");
        this.close();
        Pharmacy pharmacy = new Pharmacy();
        pharmacy.setVisible(true);
        
    }//GEN-LAST:event_jButtonSendOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderConfirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelOrder;
    private javax.swing.JButton jButtonSendOrder;
    private javax.swing.JLabel jLabelConfirmedOrderAddress;
    private javax.swing.JLabel jLabelConfirmedOrderText;
    private javax.swing.JLabel jlbDistributorNameTitle;
    // End of variables declaration//GEN-END:variables
}
