/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orderingSystem;

import java.awt.Color;
import java.awt.event.WindowEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;


/**
 *
 * @author sofiagarcia
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        branchCheckboxes = new javax.swing.ButtonGroup();
        distributorRadioButtons = new javax.swing.ButtonGroup();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblDistributor = new javax.swing.JLabel();
        comboBoxType = new javax.swing.JComboBox<>();
        lblBranch = new javax.swing.JLabel();
        checkBoxPrincipal = new javax.swing.JCheckBox();
        checkBoxSecondary = new javax.swing.JCheckBox();
        buttonDelete = new javax.swing.JButton();
        buttonConfirm = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        radioButtonEmpsephar = new javax.swing.JRadioButton();
        radioButtonCofarma = new javax.swing.JRadioButton();
        radioButtonCemefar = new javax.swing.JRadioButton();
        errorType = new javax.swing.JLabel();
        errorName = new javax.swing.JLabel();
        errorQuantity = new javax.swing.JLabel();
        errorDistributor = new javax.swing.JLabel();
        errorBranch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setText("Nombre");

        lblType.setText("Tipo");

        lblQuantity.setText("Cantidad");

        lblDistributor.setText("Distribuidor");

        comboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo ", "antibióticos" }));

        lblBranch.setText("Escoge tu sucursal");

        branchCheckboxes.add(checkBoxPrincipal);
        checkBoxPrincipal.setText("Principal");

        branchCheckboxes.add(checkBoxSecondary);
        checkBoxSecondary.setText("Secundaria");

        buttonDelete.setText("Borrar");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonConfirm.setText("Confirmar");
        buttonConfirm.setToolTipText("");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LA GRAN FARMACIA");

        distributorRadioButtons.add(radioButtonEmpsephar);
        radioButtonEmpsephar.setText("Empsephar ");

        distributorRadioButtons.add(radioButtonCofarma);
        radioButtonCofarma.setText("Cofarma");

        distributorRadioButtons.add(radioButtonCemefar);
        radioButtonCemefar.setText("Cemefar");

        errorName.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorDistributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblType)
                                    .addComponent(buttonDelete)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButtonCofarma)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioButtonEmpsephar)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioButtonCemefar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE)))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblQuantity))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(errorType)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonConfirm))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(errorQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblDistributor)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblBranch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(checkBoxPrincipal)
                        .addGap(81, 81, 81)
                        .addComponent(checkBoxSecondary)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitle)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(comboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorType)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuantity)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorQuantity)
                .addGap(15, 15, 15)
                .addComponent(lblDistributor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonCofarma)
                    .addComponent(radioButtonEmpsephar)
                    .addComponent(radioButtonCemefar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorDistributor)
                .addGap(18, 18, 18)
                .addComponent(lblBranch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxPrincipal)
                    .addComponent(checkBoxSecondary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(errorBranch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(buttonConfirm))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void close() {
        WindowEvent  closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        getToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private String selectedDistributor = null;
    private String selectedBranch = null;
    
    private boolean validateFields() {
 
        boolean match = this.txtName.getText().matches("[a-zA-Z0-9]+");
        if (!match) {
            this.errorName.setText("Carácteres especiales no permitidos");
            this.errorName.setForeground(Color.red);
            return false;
        }
        
        if (this.comboBoxType.getSelectedItem().toString().isEmpty()) {
            this.errorType.setText("Debes seleccionar un tipo");
            this.errorType.setForeground(Color.red);
            return false;
        }
        
        boolean quantityInt = this.txtQuantity.getText().matches("[0-9]+");
        if (!quantityInt) {
            this.errorQuantity.setText("La cantidad debe ser un número entero");
            this.errorQuantity.setForeground(Color.red);
            return false;
        }
        
        if(this.selectedDistributor == null) {
            this.errorDistributor.setText("Debes seleccionar un distribuidor");
            this.errorDistributor.setForeground(Color.red);
            return false;
        }
        
        if(this.selectedBranch == null) {
            this.errorBranch.setText("Debes seleccionar una sucursal");
            this.errorBranch.setForeground(Color.red);
            return false;
        }
        
        return true;
    }
    
    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed
        Order order = new Order();
        
        for(Enumeration buttons = this.distributorRadioButtons.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = (AbstractButton) buttons.nextElement();
            if (button.isSelected()) {
                this.selectedDistributor =  button.getText();
            }
        } 
        
        for(Enumeration checkBoxes = this.branchCheckboxes.getElements(); checkBoxes.hasMoreElements();) {
            AbstractButton checkBox = (AbstractButton) checkBoxes.nextElement();
            if (checkBox.isSelected()) {
                this.selectedBranch =  checkBox.getText();
            }
        }
        
        if (validateFields()) { 
            order.setName(this.txtName.getText());
            order.setType(this.comboBoxType.getSelectedItem().toString());
            order.setQuantity(this.txtQuantity.getText());
            order.setDistributor(this.selectedDistributor);
            order.setBranch(this.selectedBranch);
            
            this.close();
            OrderConfirmation orderConfirmed = new OrderConfirmation(order);
            orderConfirmed.setVisible(true);
        }
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        this.txtName.setText("");
        this.comboBoxType.setSelectedIndex(0);
        this.txtQuantity.setText("");
        this.distributorRadioButtons.clearSelection();
        this.branchCheckboxes.clearSelection();
        this.selectedBranch = null;
        this.selectedDistributor = null;
        this.errorBranch.setText("");
        this.errorName.setText("");
        this.errorQuantity.setText("");
        this.errorType.setText("");
        this.errorDistributor.setText("");
    }//GEN-LAST:event_buttonDeleteActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup branchCheckboxes;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JCheckBox checkBoxPrincipal;
    private javax.swing.JCheckBox checkBoxSecondary;
    private javax.swing.JComboBox<String> comboBoxType;
    private javax.swing.ButtonGroup distributorRadioButtons;
    private javax.swing.JLabel errorBranch;
    private javax.swing.JLabel errorDistributor;
    private javax.swing.JLabel errorName;
    private javax.swing.JLabel errorQuantity;
    private javax.swing.JLabel errorType;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblDistributor;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton radioButtonCemefar;
    private javax.swing.JRadioButton radioButtonCofarma;
    private javax.swing.JRadioButton radioButtonEmpsephar;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
